services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - 3100:3100
    volumes:
      - ./backend/src:/code/src:ro
      - ./backend/package.json:/code/package.json
      - ./backend/package-lock.json:/code/package-lock.json
    networks:
      - transcended_network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    restart: always
    networks:
      - transcended_network
    env_file: .env
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "${MARIADB_USER}", "--password=${MARIADB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  transcended_network:
    driver: bridge
